### ISSUE TITLE
Morning Session peer to peer code review

### ISSUE THREAD

**Issue by SurafelGetachewT** [edi-sipka/Digital_World_Summit#2]
This is one of the most impressive projects I have ever seen, to mention some of the impressive things:
1. The quality of the icons and images you have used.
2. The way you apply the DOM concept in your project.
But we recommend you to:
1. Add some animation and transition effects.
2. Add a hover effect for your buttons.

**Comment by edi-sipka** [comment]
Thank you @SurafelGetachewT for honest review of my project. 
I added transition on logo an hover effects on nav bar.
